### ISSUE TITLE
Update links for GitHub

### ISSUE THREAD

**Issue by analogtwin** [siemens/ros-sharp#1]
Check links in the following files and update them for GitHub if necessary:
- [x] CODE_OF_CONDUCT.md
- [x] CONTRIBUTING.md
- [x] LICENSE.md
- [x] README.md
- [x] ROSbridgeClient/README.md
- [x] URDFsharp/README.md
- [x] file_server/README.md

Wiki:
- [x] home.md
- [x] using-rossharp-to-import-urdf-from-ros.md

**Comment by roehrlverena** [comment]
I updated the links.
Nothing more to do
