### ISSUE TITLE
Tutorial wanted for ROS#example: ROS#: Robot Visualization in Unity (a robot arm)

### ISSUE THREAD

**Issue by Bertrand64300** [siemens/ros-sharp#107]
Hi team,
I am trying to sync a UR5 robot arm between Unity and ROS through ROS#. And I've found the following video officially published by ROS#, but it is just a rough show case. My question is if it is possible for you to provide a detailed tutorial on this project?
My reason is the only existing example doesn't offer enough practice and skills to use ROS# well for people who are less experienced. The tutorial I wanted will be very helpful for people who work on robot arms with ROS#.
ROS# is a great tool and well documented. But few materials or sucessfull appications available for a better user of it. 
[https://www.youtube.com/watch?v=wo3hwsPFEPY](url)
![image](https://user-images.githubusercontent.com/42397710/44251286-ed2a0100-a24b-11e8-8dc5-24398e229a0e.png)

Thanks a lot.

**Comment by MartinBischoff** [comment]
Hi @Bertrand64300 ! The video you referenced is a showcase video illustrating what can be done with ROS#. It is no tutorial.  It was done with an outdated version of ROS#.

Please go through the tutorials [Importing a URDF from ROS](https://github.com/siemens/ros-sharp/wiki/User_App_ROS_ImportingURDFFromROS) and [Unity Simulation Example](https://github.com/siemens/ros-sharp/wiki/User_App_ROS_UnitySimulationExample) to get started with ROS#. When done, you should have the understanding to setup the communication with your UR5 ROS system and adjust the Unity project to your application-specific needs.
