### ISSUE TITLE
Feature: Add BSON backend as alternative to JSON

### ISSUE THREAD

**Issue by awesome-manuel** [siemens/ros-sharp#136]
BSON is a bit more efficient than JSON when it comes to large binary data sets like images, laser scan data or occupancy grids.

rosbridge_websocket supports BSON for serialization:
- https://github.com/RobotWebTools/rosbridge_suite/issues/169
- https://github.com/RobotWebTools/rosbridge_suite/pull/257
- https://github.com/RobotWebTools/rosbridge_suite/pull/327

BSON is also available in C#: https://www.newtonsoft.com/json/help/html/SerializeToBson.htm

**Comment by awesome-manuel** [comment]
I'd actually either use only BSON or only JSON mode (using a configuration option). JSON can be easily identified if the first character is a `{` and the last character is a `}`. For BSON the first character could be `{` if the length of the full message has `0x7B` in the least significant byte and the last character is always `0x00`. There might be some wrongly formatted messages, but in this case I'd just prefer JSON and if the JSON parser fails use the BSON parser.

We are working on an rviz like application for the HoloLens. So we need to transfer a lot of binary data like I mentioned above. We also need introspection, since we don't know the message type at compile time.

The alternative is to use out of band connections for camera etc (I think rosbridge has something for this) or to use ROS2 for the HoloLens part and the ROS1/ROS2 bridge to integrate legacy systems. Since this project is more mature than the ROS2 integration for C# we will start here until we hit some major performance issues.

**Comment by dwhit** [comment]
@awesome-manuel, I think BSON support would be awesome. I would be wary of trying to first JSON parse and then BSON parse, because converting from Base64 is super slow, and so attempting that every time a BSON message came in would eat up a lot of the performance gains.

**Comment by awesome-manuel** [comment]
Since adding BSON breaks client compatibility anyway you could as well add a message type identifier as first byte of your message.

**Comment by BenArtes** [comment]
I just discovered that rosbridge already uses BSON for `uint8[]` and `char[]` types. (The pull request that added that capability is here: https://github.com/RobotWebTools/rosbridge_suite/pull/190).

For ease of use I'd been using PointCloud and was seeing ~28 ms Publish times ([as documented](https://github.com/siemens/ros-sharp/issues/81#issuecomment-438044886)). I just tried switching to PointCloud2 and saw the Publish time drop to ~4ms.

Obviously this would be a good feature to leverage for all appropriate message types, but using currently supported messages is probably a good work-around until support can be added.

Also, in November 2018, work was done to add CBOR support to subscriptions (https://github.com/RobotWebTools/rosbridge_suite/issues/367); another comment by that developer indicates that CBOR was faster than BSON in his benchmarks (https://github.com/RobotWebTools/rosbridge_suite/issues/370), though his benchmarks were for browser based JS. 

Difficulty with CBOR might be encoding / decoding libraries; while there is support in Newtonsoft.JSON for BSON as posted in a previous comment, I only found a ~2 year old version that supported [CBOR](https://github.com/NZSmartie/Newtonsoft.Json.Cbor).

**Comment by MartinBischoff** [comment]
Issue has been addressed in commit 2bcb266 .
