### ISSUE TITLE
Attach object to imported URDF Model

### ISSUE THREAD

**Issue by mhelmrei** [siemens/ros-sharp#145]
Hello,
I'm running Unity Version 2018.3.0b9 with the latest ros-sharp from GitHub on Windows 10.

I am simulating a fabrication process in Unity and I successfully imported the URDF of the robotic set-up
into Unity. Also I am able to transform the robots accordingly.

Now I would like to attach a linear timber beam to the robot at a certain moment in the fabrication process, also once the beam is placed I would like to detach the object again.

Would this be possible and if yes how should I go about it?

Thank you!
Matthias Helmreich

![image](https://user-images.githubusercontent.com/34544179/49453843-3a72b400-f7e4-11e8-9152-c0262d1a792b.png)

**Comment by MartinBischoff** [comment]
Hi @mhelmrei 
I hope the hints above helped you in solving your  problem. As I still see no direct relation to ROS# and have not received feedback I am closing this issue.

I'm looking forward to read a short intro on what your are doing / planning to do with ROS# [here](https://github.com/siemens/ros-sharp/issues/20).
