### ISSUE TITLE
connect Unity with Turtlebot3

### ISSUE THREAD

**Issue by shaghayeghmzi** [siemens/ros-sharp#165]
could you please help me, I want to connect Unity with gazebo 8 but unfortunately I cant launch turtlebot2 in it so I have to launch turtelbot3 in gazebo 8 but the issue is here that I cant connect it with unity.
can you please guide me to how can i run turtlebot3 on unity?

**Comment by shaghayeghmzi** [comment]
and also you make me my pleasure if you tell me that can i run Pioneer robot in unity or not?

**Comment by MartinBischoff** [comment]
Hi @shaghayeghmzi you can connect with any ROS system. This includes turtlebot2, turtlebot3 and other robots that have ROS and rosbridge_suite operational.
