### ISSUE TITLE
What are "Libraries" used for? 

### ISSUE THREAD

**Issue by Xunzhaocunzi** [siemens/ros-sharp#167]
Hello, 
Thanks a lot for sharing the source code and writing the detailed tutorials. 
I am still confused what and how "Libraries" folder should be used.  I know I should put "ROS" folder into my ros src folder in VM ubuntu, and put "Unity3D" folder into my unity assets in windows. It looks like I never need "Libraries" folder. 
Thank you!

**Comment by MartinBischoff** [comment]
Please read the section Custom Message Types [here](https://github.com/siemens/ros-sharp/issues/169#issuecomment-467798252).
