### ISSUE TITLE
Cannot drag Gameobject(turtlebot3) into message receiver in RosConnector When setting up Gazebo simulation scene

### ISSUE THREAD

**Issue by stevensu1838** [siemens/ros-sharp#177]
Hi all
My settings are ROS# Version 1.2c, Unity 2017.4 and ROS indigo and I followed this video to run **Turtlebot2** successfully. But when I tried to do the same thing to **Tutlebot3**, I got some problems. Apart from sending different URDF (**udf of Tutlebot3**) to Unity, I following the same steps in tutorials that I used to set up Tutlebot2. However, this time I can't drag Gameobject(**Turtlebot3 and ImageReceive**r) into **message receiver** in RosConnector in Inspector. Have any of you experienced this before when you try to use your own robot instead of Tutlebot2? How did you fix it? Thanks a lot
![capture1](https://user-images.githubusercontent.com/25648734/54016536-2f1a9480-41e8-11e9-9145-1383d3741cad.PNG)

**Comment by MartinBischoff** [comment]
@stevensu1838 
This is a basic Unity Usability question that has nothing to do with ROS#. Genereric Unity beginner questions should not be asked here. Please refer to  https://unity3d.com/de/community in the future.

You need to add a Message Receiver to the gameobject prior to drag & dropping it into your subscribers.
