### ISSUE TITLE
Messages Standard Bool.cs in Unity3D?

### ISSUE THREAD

**Issue by Kenichi-Usami** [siemens/ros-sharp#202]
Does not Unity3D include this Bool.cs?

https://github.com/siemens/ros-sharp/blob/master/Libraries/RosBridgeClient/Messages/Standard/Bool.cs

**Comment by berkayalpcakal** [comment]
Hello,

It seems that some standard messages, including Bool.cs, are actually exist under relevant folder, but were not included in the RosBridgeClient Visual Studio Project. Now the issue should be resolved by [this merge](https://github.com/siemens/ros-sharp/pull/205).

**Comment by Kenichi-Usami** [comment]
Thank you!!
