### ISSUE TITLE
ROS# Menu Options not appearing

### ISSUE THREAD

**Issue by xGossipgoat** [siemens/ros-sharp#203]
I have looked through the issues but no one else seems to be having this 

I am following the steps to install ros# in unity and I copied the RosBridge folder into assets an d changed the framework to Net.4x.

However none of the the menu options appear and I get these console errors related to rosbridge

![image](https://user-images.githubusercontent.com/50760575/57964105-de0ae780-7972-11e9-8ec2-74879b8732e7.png)

**Comment by MartinBischoff** [comment]
Unity Version?

**Comment by xGossipgoat** [comment]
2018.2.16

**Comment by MartinBischoff** [comment]
Please update.
We have to update the [README.md](https://github.com/siemens/ros-sharp) as well...
