### ISSUE TITLE
Help regarding setting up ros bridge websocket

### ISSUE THREAD

**Issue by Erikishiru** [siemens/ros-sharp#216]
I am new to ROS and Unity. I was trying to write a Unity subscriber to subscribe simple string messages from a ROS topic in a Unity Scene. 

I have set up my machine in accordance with the wiki page and was successfully able to run the TurtleBot simulation.

I know it's a lot but I would want to know how to set up the connection between ROS Bridge WebSocket and where to put the subscriber script in my Unity Scene. 

Any help would be appreciated.

Thanks in advance.

**Comment by berkayalpcakal** [comment]
Hello @Erikishiru,

Please have a look at the subscriber scripts under [RosCommunication folder](https://github.com/siemens/ros-sharp/tree/master/Unity3D/Assets/RosSharp/Scripts/RosBridgeClient/RosCommuncation). You should come up with your own subscriber scripts easily.

[Here](https://github.com/siemens/ros-sharp/wiki/Info_CodeExample) is a console example wiki page as well.

If you encounter any issue while writing your own custom subscriber, please open up an issue by using the issue template.

Thanks.
