### ISSUE TITLE
Please Delete, Did not read README

### ISSUE THREAD

**Issue by mavera3** [siemens/ros-sharp#226]
I did not see the part in the README requiring Unity 2018.3 or higher. This is most likely the cause of my errors because of the newly implemented C# compilers in 2018.3. I was using 2018.1
##  I found a bug! ##

* My OS is: Windows 10
* My Unity Version is: 2018.1.0b13
* My ROS Distribution is: melodic
* My Build Target Platform is: Windows 10

**Here is my bug description:**
After importing the RosSharp v1.5 Unity package, I immediately get these 3 console errors related to the c# language version.
The error in the console is

- `Assets/RosSharp/Scripts/RosBridgeClient/RosCommunication/JointStatePublisher.cs (65,21): error CS1644: Feature 'out variable declaration cannot be used because it is not part of the C# 6.0  language specification`
- `Assets/RosSharp/Scripts/RosBridgeClient/RosCommunication/JointStatePublisher.cs (65,21): error CS1644: Feature 'out variable declaration' cannot be used because it is not part of the C# 6.0  language specification`
- `Assets/RosSharp/Scripts/RosBridgeClient/RosCommunication/JointStatePublisher.cs (65,21): error CS1644: Feature 'out variable declaration' cannot be used because it is not part of the C# 6.0  language specification`

Perform the following steps reproduce the bug:

1. Open an new project in Unity editor
2. import the RosSharp v1.5 package
3. Edit > Project Settings > Player > Other Settings > Configuration > Scripting Runtime Version* = Stable (.NET 4.x Equivalent)

Observed results:
![rossharperror](https://user-images.githubusercontent.com/6774867/61088325-24764300-a406-11e9-8015-53a23ad7e98e.png)

Expected results:
No console errors

**Comment by MartinBischoff** [comment]
ROS# currently requires Unity 2018.3 minimum.
