### ISSUE TITLE
How can I move UrdfJoint to accurate radian?

### ISSUE THREAD

**Issue by HugeKangroo** [siemens/ros-sharp#262]
## I have a question! ##

* [x] I searched the [Wiki](https://github.com/siemens/ros-sharp/wiki), [open](https://github.com/siemens/ros-sharp/issues) and [closed](https://github.com/siemens/ros-sharp/issues?q=is%3Aissue+is%3Aclosed) issues for an answer. I tried my best to find the answer by myself without success. I believe that the discussion we will have in this issue, and the solutions we might find, will help me, and likely other community members who have a similar problem.

**Here is my question:**

Hello, everyone
My project need control a six axis robot in unity with input radian. And, I am using JointStateWriter to control  it with function write(). 
I have set urdfrobot to kinemetic and turned off the inertia but when I  input a radian , for example 3.1415 , it will move like 3.1410. 

Did I make something wrong ? or could I manipulate the joint to accurate radian？

* My OS is: Ubuntu18.04
* My Unity Version is: 2019.3.0b8
* My ROS Distribution is: not using ROS
* My Build Target Platform is: Ubuntu18.04

**Comment by berkayalpcakal** [comment]
Hello @HugeKangroo,
Is the issue still valid on your side?
