### ISSUE TITLE
Topic conflict for /odom published by Pose Stamped Publisher

### ISSUE THREAD

**Issue by Konye666** [siemens/ros-sharp#275]
## I have a question! ##

* [x] I searched the [Wiki](https://github.com/siemens/ros-sharp/wiki), [open](https://github.com/siemens/ros-sharp/issues) and [closed](https://github.com/siemens/ros-sharp/issues?q=is%3Aissue+is%3Aclosed) issues for an answer. I tried my best to find the answer by myself without success. I believe that the discussion we will have in this issue, and the solutions we might find, will help me, and likely other community members who have a similar problem.

**Here is my question:**

Hello and thank you for your work on ROS#. I am a beginner on ROS# so I am trying to follow all of your tutorials. I am now going into the [Unity Simulation Example](https://github.com/siemens/ros-sharp/wiki/User_App_ROS_UnitySimulationExample), the terminal in ros gave errors when it comes to the running after the running of Unity which is different to your [video](https://www.youtube.com/watch?v=sup2Tdxt1ko&feature=youtu.be).

Here is the information of the error:
`[ERROR] [1577932493.349515]: [Client 0] [id: /odom] publish: Message type nav_msgs/Odometry does not have a field pose.position
[ERROR] [1577932493.354119]: [Client 0] [id: /odom] publish: Message type nav_msgs/Odometry does not have a field pose.position
`
Also there is no output when I use rostopic echo for /odom.

**However, when I change the topic name such as "/unity_odom", the error disappears and the output for rostopic info goes fine.**

Maybe there is a conflict for the topic, but why? Thank you!

* My OS is:  Ubuntu 16.04
* My Unity Version is:  2018.3.9f1 Personal
* My ROS Distribution is:  Kinetic

**Comment by berkayalpcakal** [comment]
Hello @Konye666, do you have any updates? 
I could not reproduce the issue, so could you please use the latest version of ROS# and write down the steps to reproduce the issue?

**Comment by berkayalpcakal** [comment]
Closed due to inactivity.

**Comment by amelia413** [comment]
I'm facing the same issue! 
Unity : 2019.4.40f1
Ros: Noetic
Ros# latest version
