### ISSUE TITLE
ROS Sharp Unity3d import PointCloud2 and vuslized in a mesh

### ISSUE THREAD

**Issue by acpl00** [siemens/ros-sharp#276]
The following code subscribes to a pointcloud2 and creates a mesh. But I do not know how can I connect the xyz points of the pointcloud that are in the SubscriptionHandler with the mesh that is in the start().

Any help I will appreciate it :)

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using System;
using RosSharp.RosBridgeClient;
using std_msgs = RosSharp.RosBridgeClient.MessageTypes.Std;
using sensor_msgs = RosSharp.RosBridgeClient.MessageTypes.Sensor;
using RosSharp.RosBridgeClient.Protocols;

[RequireComponent(typeof (RosConnector))]
[RequireComponent(typeof (MeshFilter))]
public class PointCloudSubscriber : MonoBehaviour
{
	
	public string uri = "ws://10.42.0.1:9090";
	private RosSocket rosSocket;
	string subscriptionId = "";

	public RgbPoint3[] Points;

	//Mesh components
	Mesh mesh;
	Vector3[] vertices;
	int[] triangles;

	public int xSize = 20;
	public int zSize = 20;

	
	// Start is called before the first frame update
	void Start()
	{
		
		mesh = new Mesh(); 
		GetComponent<MeshFilter>().mesh = mesh;

		CreateShape();
		UpdateMesh();

		
	        Debug.Log("RosSocket Initialization!!!");
		
		rosSocket = new RosSocket(new  RosSharp.RosBridgeClient.Protocols.WebSocketNetProtocol(uri)); // 10.189.42.225:9090
		
		Subscribe("/zed/rtabmap/cloud_map");

	}

	void Update()
	{

	}

	void CreateShape(){

		vertices = new Vector3[(xSize+1)*(zSize+1)];

		for(int i = 0,  z =0; z <= zSize; z++)
		{
			for(int x =0; x <= xSize; x++){
				vertices[i] = new Vector3(x,0,z);
				i++;
			}
		}

	}

	void UpdateMesh()
	{
		mesh.Clear();
		mesh.vertices = vertices;
	}

	private void OnDrawGizmos()
	{
		if(vertices == null)
			return;
		for(int i =0; i < vertices.Length; i++)
		{
			Gizmos.DrawSphere(vertices[i], .1f);
		}
	}

	public void Subscribe(string id)
	{
		
                subscriptionId  = rosSocket.Subscribe<sensor_msgs.PointCloud2>(id, SubscriptionHandler);

	}

	private IEnumerator WaitForKey()
	{
		Debug.Log("Press any key to close...");

		while (!Input.anyKeyDown)
		{
			yield return null;
		}

		Debug.Log("Closed");
		// rosSocket.Close();
	}

	private static void SubscriptionHandler(sensor_msgs.PointCloud2 message)
	{
		
		Debug.Log("Message received!");
		long I = message.data.Length / message.point_step;
		Debug.Log("Long I   " + I);
		RgbPoint3[] Points = new RgbPoint3[I];
		byte[] byteSlice = new byte[message.point_step];

		for (long i = 0; i < I; i++)
		{
			Array.Copy(message.data, i * message.point_step, byteSlice, 0, message.point_step);
			Points[i] = new RgbPoint3(byteSlice, message.fields);

			//Debug.Log("X   " + Points[i].x);
			//Debug.Log("Y   " + Points[i].y);
			//Debug.Log("Z   " + Points[i].z);

		}

		Vector3[] newverts = new Vector3[I];
		

		for (var i = 0; i < I; i++)
		{

			newverts[i].x = Points[i].x;
			newverts[i].y = Points[i].y;
			newverts[i].z = Points[i].z;
			//Debug.Log("newvertes_X   " + newverts[i].x	);

		}

		

	}
}

**Comment by MartinBischoff** [comment]
Hi @acpl00 ,

this question has nothing to do with ROS# but is a generic Unity / C# programming question. Please mind the issue template.

Best,
Martin
