### ISSUE TITLE
Unity on ubuntu support

### ISSUE THREAD

**Issue by spigelli** [siemens/ros-sharp#282]
Is there a fix for running ROS# with unity on ubuntu or can someone point me to the right issue?

**Comment by berkayalpcakal** [comment]
Could you please explain what do you mean by "fix for running ROS# with Unity on Ubuntu"? 
Do you have a reproducible issue?

Well, about the "pointing to the right issue" thing...
You can always use the search tool on Issues page.

![Capture](https://user-images.githubusercontent.com/29926508/72718886-12c0e580-3b77-11ea-88ac-71cbeca05298.PNG)


For the next time when you want to open an issue, please use the issue template and clearly define the steps to reproduce the issue that you have.
