### ISSUE TITLE
Problem adding new message type

### ISSUE THREAD

**Issue by omergreenwald** [siemens/ros-sharp#294]
after i add the new message type by the instruction in the wiki (https://github.com/siemens/ros-sharp/wiki/Dev_NewMessageTypes ,Option 3) i got the following error in unity: 
"The type or namespace name 'MessageTypes' does not exist in the namespace 'RosSharp.RosBridgeClient' (are you missing an assembly reference?)"
the only thing that is exist in RosSharp.RosBridgeClient now is Actionlib.
How do i get all the types and namespace that spouse to be in  RosSharp.RosBridgeClient?
the message i tried to add:

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Sensor
{
    public class Outbonnd_sv_list : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "kairos_brigde/Outbonnd_sv_list";
        public RosSharp.RosBridgeClient.MessageTypes.Std.Header header;
        public string[] video_mux1;
        public bool veh_start;
        public bool veh_enable;
        public bool veh_motion;
        public short joy_steer;
        public short veh_steer;
        public ushort veh_brake;
        public ushort veh_throttle;
        public ushort veh_shift;

        public Outbonnd_sv_list()
        {
            header = new Std.Header();
            video_mux1 = new string[0];
            veh_start = false;
            veh_enable = false;
            veh_motion = false;
            joy_steer = 0;
            veh_steer = 0;
            veh_brake = 0;
            veh_throttle = 0;
            veh_shift = 0;
        }
    }
}

**Comment by berkayalpcakal** [comment]
Hello @omergreenwald,

Unfortunately I cannot reproduce this issue. After downloading the RosSharp repository, have you tried getting a successful build from the solution under the folder [ros-sharp/Libraries](https://github.com/siemens/ros-sharp/tree/master/Libraries)? The message types that you mentioned should be all included in the project.

With the recent changes, you do not need to have "Newtonsoft" related codes in your class. The wikipage shall be updated soon. Here is the code for the message class **\Libraries\RosBridgeClient\MessageTypesOutbonnd_sv_list.cs** that I was able to successfully added to the project;

```csharp
namespace RosSharp.RosBridgeClient.MessageTypes.Sensor
{
    public class Outbonnd_sv_list : Message
    {
        public const string RosMessageName = "kairos_brigde/Outbonnd_sv_list";
        public RosSharp.RosBridgeClient.MessageTypes.Std.Header header;
        public string[] video_mux1 { get; set; }
        public bool veh_start { get; set; }
        public bool veh_enable { get; set; }
        public bool veh_motion { get; set; }
        public short joy_steer { get; set; }
        public short veh_steer { get; set; }
        public ushort veh_brake { get; set; }
        public ushort veh_throttle { get; set; }
        public ushort veh_shift { get; set; }
        
        public Outbonnd_sv_list()
        {
            header = new RosSharp.RosBridgeClient.MessageTypes.Std.Header();
            video_mux1 = new string[0];
            veh_start = false;
            veh_enable = false;
            veh_motion = false;
            joy_steer = 0;
            veh_steer = 0;
            veh_brake = 0;
            veh_throttle = 0;
            veh_shift = 0;
        }
    }
}
```

If you have an issue regarding getting a successful build from the RosBridgeClient project, please open another issue using the provided issue template.
