### ISSUE TITLE
Add List of Dependencies in ROSbridgeClient/README.md

### ISSUE THREAD

**Issue by analogtwin** [siemens/ros-sharp#3]
specify project internal and external dependencies of the ROSbridgeClient solution similar to URDFsharp/README.md.

**Comment by jaguar243** [comment]
Please see the pull request and let me know if that is sufficient. Sorry, I forgot to do this before I left.

**Comment by analogtwin** [comment]
Thank you for your support Rahul! I didn't expect that!
