### ISSUE TITLE
URDF transfer issues

### ISSUE THREAD

**Issue by uahic** [siemens/ros-sharp#312]
Hi,

I wrote a custom launch-script (modified version from the turtlebot  example of the file_server) which succesfully launches the web-bridge, started the URDF-ROS->Unity Importer connected to the localhost 127.0.0.1:9090 but after it connects to the webbridge (the bridge confirms '1 client connected'), it seems to stuck and unable to receive the URDF before it timesout. The launch script sucessfully has launched the file_server and runs xacro to read-in the specified URDF.

Versions:
Unity 2019.3.13f1
OS: Ubuntu 18.04
ROS-melodic
ROS#: master branch (head)

The log of Unity shows no exceptions or warnings beside from the debug-warning of the function ImportAssets:  "Not all resource files have been received before timeout".

What could have gone possibly wrong? Any suggestions how I might debug this further? 

The launch script looks like this:

```
<launch>
    <include file="$(find file_server)/launch/ros_sharp_communication.launch">
        <arg name="port" value="9090" />
    </include>
 
    <arg name="urdf_file" default="$(find hollie_description)/urdf/hollie.urdf.xacro" />
    <param name="robot/name" value="Hollie" />
    <param name="robot_name" value="Hollie" />
 
    <arg name="left_hand_type" default="qb" doc="Type of left hand. Possible values: qb, svh, pg70" />
    <arg name="right_hand_type" default="qb" doc="Type of right hand. Possible values: qb, svh, pg70" />
 
    <param name="robot_description" command="$(find xacro)/xacro $(arg urdf_file) left_hand_type:=$(arg left_hand_type) right_hand_type:=$(arg right_hand_type)" />
 
</launch>
```

Thank you very much

**Comment by berkayalpcakal** [comment]
Hello @uahic ,
Please refer to the issues #301, #309.

**Comment by MartinBischoff** [comment]
closing, see comment from @hahahuhu663 in issue #314.
