### ISSUE TITLE
Why the  turtlebot2 is in a mess

### ISSUE THREAD

**Issue by 329937626** [siemens/ros-sharp#333]
![image](https://user-images.githubusercontent.com/65693713/89848221-921c1200-dbb8-11ea-9504-82ecb99938f6.png)
I have do the Tutorial:
2.1 Transfer a URDF from ROS to Unity
But,the robot is in a mess when the "Play" Button is click, like above screenshot.
Why??

**Comment by 329937626** [comment]
The Kinect is fall down on the ground , the turtlebot2 's parts is separate.
 The turtleot2 is scampering, like in a mess. Why?

**Comment by 329937626** [comment]
unity version：
2018.4.25  or 2019 is the same result why?

**Comment by EricVoll** [comment]
Do you get any Errors in the Unity Console?
I had something similar once where the code crashed after creating the game objects but before setting "IsKinetic" to true.

**Comment by 329937626** [comment]
> 
> 
> Do you get any Errors in the Unity Console?
> I had something similar once where the code crashed after creating the game objects but before setting "IsKinetic" to true.

Thank you very much! Your method worked, thank you.

**Comment by jiayiyi1991** [comment]
I use the last code , I have the same problem. Set "IsKinetic" to true, turtlebot can‘t move ; Set "IsKinetic" to false, turtlebot broke；When I change last releases version 1.6 ,  everything is ok；

**Comment by 329937626** [comment]
> I use the last code , I have the same problem. Set "IsKinetic" to true, turtlebot can‘t move ; Set "IsKinetic" to false, turtlebot broke；When I change last releases version 1.6 ,  everything is ok；

My version is last releases. pull it a few days ago.

**Comment by 329937626** [comment]
你用的是哪个版本的教程？你配置的Controller 配置是这样的吗







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "siemens/ros-sharp"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月12日(星期三) 下午4:24
收件人:&nbsp;"siemens/ros-sharp"<ros-sharp@noreply.github.com&gt;;
抄送:&nbsp;"o尛籹孩/ka  "<329937626@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [siemens/ros-sharp] Why the  turtlebot2 is in a mess (#333)





 
I use the last code , I have the same problem. Set "IsKinetic" to true, turtlebot can‘t move ; Set "IsKinetic" to false, turtlebot broke；When I change last releases version 1.6 ,  everything is ok；

**Comment by berkayalpcakal** [comment]
@329937626 
Why are you writing something in Chinese? 
Do you even read the comments above?


> Do you get any Errors in the Unity Console?
> I had something similar once where the code crashed after creating the game objects but before setting "IsKinetic" to true.

Just set the IsKinetic flag true on the inspector editor of your robot!
