### ISSUE TITLE
unity Tutorial: 2.4 Unity Simulation Example,Why no working?

### ISSUE THREAD

**Issue by 329937626** [siemens/ros-sharp#335]
UnitySimulationScene have run no error.

Unity Console:
Connected to RosBridge: ws://192.168.12.39:9090
UnityEngine.Debug:Log(Object)
and no error.

But,when I Joy my mouse, the turtlebot no move, and refresh Node Graph, have no tie line like the Tutorial video
2.4 Unity Simulation Example
Why the turtlebot no move?

**Comment by 329937626** [comment]
Change to release version 1.6

**Comment by MartinBischoff** [comment]
Hi @329937626 ,
sorry I do not understand your issue description.
Please use the issue template.
If your issue is about an error, please provide the detailed error message and a description how to reproduce this bug on another machine.
