### ISSUE TITLE
Automatically connect to rosbridge by modifying "base.Start()"

### ISSUE THREAD

**Issue by glennliu** [siemens/ros-sharp#339]
Hi 

The current _ROS#_ requires _rosbridge_ launched before running _ROS#_. In my case, I want to build an Unity interface automatically connect to _rosbridge server_, whenever it detects the _rosbridge server_. So, I modify the code as below,
**_RosConnector.cs_**
```
while (!is_connected)
{
   RosConnection = new Thread(ConnectAndWait);
   RosConnection.Start();
}
void OnConnected()
{
   PointCloudSubscriber.ReStart();
}
```
**_PointCloudSubscriber.cs_**
```
void Start()
{
            // base.Start();
            // isMessageReceived = false;
}
void ReStart()
{
            base.Start();
            isMessageReceived = false;
}
```
When I launch _rosbridge_ before _ROS#_ as before, they are connected successful and _PointCloudSubscriber_ receives point cloud data correctly. However, in launching _ROS#_ before the _rosbridge_,
```
[INFO] [1598177012.470973]: Client connected.  1 clients total.
```
It shows the _RosConnector_ is connected as a client, but the point cloud subscriber cannot receive data. If I uncomment the code in "Start()" function, message can be received as usual. 

Is it because something wrong with the "base.Start()" function in _PointCloudSubscriber.cs_ ?

Thanks

**Comment by berkayalpcakal** [comment]
Hello @glennliu,

Any updates so far? 

I could not find time to test your scripts, but there is one thing i did not understand in your code;

``` cs
while (!is_connected)
{
   RosConnection = new Thread(ConnectAndWait);
   RosConnection.Start();
}
void OnConnected()
{
   PointCloudSubscriber.ReStart();
}
```

I wonder why you keep opening a new thread inside the while loop. I cannot forecast the race between maybe thousands of threads (each are being a different rosbridge client) trying to connect to a server. 

At the first glance I would suggest that you have a single thread that constantly tries to connect to the server.

**Comment by glennliu** [comment]
Hi @berkayalpcakal 

I was trying to restart the RosConnection in the existing thread but it failed. So, I keep add a new RosConnnection thread in the while loop. 
I'll try with your suggestion soon later.
