### ISSUE TITLE
WebSocketSharp dependency error on installing the nuget

### ISSUE THREAD

**Issue by robokamran** [siemens/ros-sharp#379]
Hello everyone,
I am trying to write a C# application to communicate with ROS. I get this error when I try to install `RosSharpRosBridgeClient` from NuGet manager UI:

`Unable to resolve dependency 'WebSocketSharp'. Source(s) used: 'nuget.org', 'Microsoft Visual Studio Offline Packages'.`

But when I install WebSocketSharp from the package manager console with the following code, it will work fine.
`PM> Install-Package WebSocketSharp -Pre`

Please either fix this or enlighten me if I am doing something wrong.
I use VS2019 and I have tried the installation with dotnet framework 4.6 & 4.6.1 & 4.7.2 & 4.8 versions.

**Comment by MartinBischoff** [comment]
Hi @robokamran , we could not reproduce this issue. We used the same sources `nuget.org` and `Microsoft Visual Studio Offline Packages`. Please make sure to use this nuget package:  https://www.nuget.org/packages/RosSharpRosBridgeClient/
