### ISSUE TITLE
Boolean Messages like "BoolMsg" or "BooleanMsg"?

### ISSUE THREAD

**Issue by RishiWadhwa** [siemens/ros-sharp#397]
# Boolean Messages

## Problem
> Is there a Boolean Messages type like "BoolMsg" or "BooleanMsg". For example, Vector2s in C-sharp have the Vector2Msg in ros-sharp, and same with Vector3s into Vector3Msg's respectively... is there a boolean version of that.

## If no solution
> Can I send some other version of the boolean... like can I send a string containing booleans or is that not possible as we were also having some trouble using the StringMsg (again, not sure if that even exists).

**Comment by MartinBischoff** [comment]
* [Bool Msg](https://github.com/siemens/ros-sharp/blob/master/Libraries/RosBridgeClient/MessageTypes/Std/msg/Bool.cs)
* [String Msg](https://github.com/siemens/ros-sharp/blob/master/Libraries/RosBridgeClient/MessageTypes/Std/msg/String.cs)
* [all other messages already included in ROS#](https://github.com/siemens/ros-sharp/tree/master/Libraries/RosBridgeClient/MessageTypes) 
*[ how to setup new message types](https://github.com/siemens/ros-sharp/wiki/Dev_NewMessageTypes)

Please fill out the issue template next time you have a question and in particular respect this question:
* [ ] I searched the [Wiki](https://github.com/siemens/ros-sharp/wiki), [open](https://github.com/siemens/ros-sharp/issues) and [closed](https://github.com/siemens/ros-sharp/issues?q=is%3Aissue+is%3Aclosed) issues for an answer. I tried my best to find the answer by myself without success. I believe that the discussion we will have in this issue, and the solutions we might find, will help me, and likely other community members who have a similar problem.
