### ISSUE TITLE
Unity to Ros Depth camera image

### ISSUE THREAD

**Issue by omy5123** [siemens/ros-sharp#401]
---
## I have a question! ##

**Hello, I would like to virtualize a real depth camera in Ros.

But the actual depth image encodes 32FC1.
On unity, when an image is sent, it is sent to RBG24 (color) in Textureformat. I tried to fix it with something else and put shader on Texture, but it's not easy to deliver it.

While searching, if you send a single-channel 32 bit floating point or 16 bit raw depth images from the ros side, it can be processed by depth image (currently input is bgr8).

Is there a way to publish single-channel 32bit floating points or 16bit raw depthimes to the Unity camera? **

**Comment by MartinBischoff** [comment]
@omy5123 Please refer to [Unity answers](https://answers.unity.com/index.html) or [OpenCV Forum](https://forum.opencv.org/) for this question.
