### ISSUE TITLE
CameraImagePublisher and CameraImageManager

### ISSUE THREAD

**Issue by aaronlsmiles** [siemens/ros-sharp#442]
What happened to CameraImagePublisher and CameraImageManager? Where are they located now as a 404 is thrown when I follow links from previous threads?

**Comment by MartinBischoff** [comment]
https://github.com/siemens/ros-sharp/blob/master/com.siemens.ros-sharp/Assets/RosSharp/Scripts/RosBridgeClient/RosCommuncation/ImagePublisher.cs
