### ISSUE TITLE
GetParamRequest error ROS1

### ISSUE THREAD

**Issue by Cryoscopic-E** [siemens/ros-sharp#461]
Hi,

When getting the param name from the rosapi service (in particular when importing urdf from ros) I get the following exception from the rosbridge.

**Ros bridge exception:**
`call_service FieldTypeMismatchException: rosapi/GetParamRequest message requires a string for field default, but got a <class 'NoneType'>`

I'm working with ubuntu 20 and ros noetic, and you can reproduce it by trying to get a parameter from rosapi service (I was trying to get tthe turtlebot3 name and urdf)

I tracked it down do be a problem in the GetParamRequest:
https://github.com/siemens/ros-sharp/blob/fa4003b0293418cfeb530e818dcd365e3833ed65/Libraries/RosBridgeClient/MessageTypes/ROS1/Rosapi/srv/GetParamRequest.cs#L30

It is working as intended when this line is modified to` this.@default = @default`

**Comment by memrecakal** [comment]
Hi @Cryoscopic-E, thanks for the feedback. GetParamRequest is an auto-generated class and the [MessageGeneration](https://github.com/siemens/ros-sharp/tree/master/Libraries/MessageGeneration) project needs to be fixed for that.
