### ISSUE TITLE
WebSocketSharpProtocol vs WebSocketNetProtocol

### ISSUE THREAD

**Issue by cwrx777** [siemens/ros-sharp#470]
Hi all,

What is the difference and which one is recommended?

**Comment by memrecakal** [comment]
Hi @cwrx777, WebSocketNetProtocol is the ClientWebSocket class from .NET's own [System.Net.Websockets](https://learn.microsoft.com/en-us/dotnet/api/system.net.websockets?view=net-8.0) namespace. WebSocketSharpProtocol  is a wrapper for the [websocket-sharp](https://github.com/PingmanTools/websocket-sharp/) package, which is a well known custom C# implementation of the WebSocket protocol client and server. Please see [RosBridgeClient Protocols](https://github.com/siemens/ros-sharp/wiki/Dev_Protocols).
