### ISSUE TITLE
Import URDF into Unity

### ISSUE THREAD

**Issue by stevensu1838** [siemens/ros-sharp#58]
Hi Sir,
I've been following your tutorials to learn how to use ROSsharp. My question is could you please show me some other examples of how to import URDF models of other robots(UR5/Baxter/PR2) into Unity? I am less experienced. Thank you so much for your support.  

Cheers
Steven

**Comment by mcevoyandy** [comment]
@stevensu1838 I've also run across the same problem and opened this [pull request](https://github.com/siemens/ros-sharp/pull/57) to address the problem.

**Comment by MartinBischoff** [comment]
Hi @stevensu1838 ! Thanks for getting started with ROS#! 

The objective of the Wiki is to explain ROS# functionalities, and not to list robotic applications. We just took some ROS robot model that we found nice as a reference to explain the workflows. The guidelines should be directly applicable to any other ROS robot.

If you have any issue importing your UR5, Baxter or PR2 robot models according to the workflow described [here]( https://github.com/siemens/ros-sharp/wiki/User_App_ROS_ImportingURDFFromROS), please let us know. If you think any Wiki contents is wrong or missing, please send us your corrections or extensions.

P.S. Following the wiki guideline, I already imported the PR2 and the Baxter URDF model into Unity without any problems.

@mcevoyandy: Thanks for your support in this issue. Please note that @stevensu1838 has not reported any problem. All I read is that he wants some other URDF model import examples.

**Comment by MartinBischoff** [comment]
@stevensu1838 : Did above comments anwser your question? If so, please close the issue.
