### ISSUE TITLE
Provide a gentle "getting started"

### ISSUE THREAD

**Issue by analogtwin** [siemens/ros-sharp#6]
Non-experts shall be able to try out our code faster and easier.

Thus we should to set up the following two "getting started" example projects:

**1 Windows-only Example Project:**
* Provide a Unity3D example project with all required binaries from this project (ROSbridgeClient.dll, Urdf.dll) such that the user only has to do the following:

   * include external .dlls (drag and drop in Assets/Plugins folder). 
   * import the Robot model from a urdf file (imprted via the Urdf menu)

When clickling play the user can e.g. control the robot with the keyboard.

**2 ROS Interaction Example Project:**
* Provide a Unity3D example project similar to the one above with the difference that the Robot model is imported from ROS.  Additionally to the example above, the user has to establish the Websocket  connectinon to ROS (via the ROSbridge menu in Unity3D).

Further we should provide a detailed Wiki page for each example project

For Example Project 1 we should provide download links to:
* Unity3D
* external dlls
* example robot URDF
and detailed explanations what to do in Unity3D to get the example project running.

For Example Project 2 we should additionaly refer to external Wiki pages explaining:
* how to set up a VM and to install Ubuntu
* how to install ROS
* how to install the example robot on ROS
What remains to be explained in our Wiki page is the websocket connection to the VM.

**Comment by roehrlverena** [comment]
I added [GettingStarted1](https://github.com/siemens/ros-sharp/wiki/GettingStarted1) (Windows-only Example Project) and
[GettingStarted2](https://github.com/siemens/ros-sharp/wiki/GettingStarted2) (ROS Interaction Example Project) to the [wiki](https://github.com/siemens/ros-sharp/wiki) including very detailed instructions.
